{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidSelectDocumentHasEMRTD"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIEMRTDCheckViewController","text":"IDCheckUIEMRTDCheckViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasEMRTD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckui\/controllerdidselectdocumenthasemrtd(_:hasemrtd:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidSelectDocumentHasEMRTD(_:hasEMRTD:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUIEMRTDCheckViewControllerDelegate.controllerDidSelectDocumentHasEMRTD(_:hasEMRTD:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidSelectDocumentHasEMRTD(_:hasEMRTD:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidSelectDocumentHasEMRTD"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIEMRTDCheckViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIEMRTDCheckViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasEMRTD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A2UIC35controllerDidSelectDocumentHasEMRTD_03hasI0yAA0A26UIEMRTDCheckViewControllerC_SbtF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIEMRTDCheckViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/IDCheckUIEMRTDCheckViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUIEMRTDCheckViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIEMRTDCheckViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/idcheckuiemrtdcheckviewcontrollerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/controllerDidSelectDocumentHasEMRTD(_:hasEMRTD:)":{"role":"symbol","title":"controllerDidSelectDocumentHasEMRTD(_:hasEMRTD:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidSelectDocumentHasEMRTD"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIEMRTDCheckViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIEMRTDCheckViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasEMRTD"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidSelectDocumentHasEMRTD(_:hasEMRTD:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/controllerdidselectdocumenthasemrtd(_:hasemrtd:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDCheckViewController":{"role":"symbol","title":"IDCheckUIEMRTDCheckViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}],"abstract":[{"type":"text","text":"This controller appears at the very beginning of the process, just after the document selection screen, if the preferred scan mode is .ask, when the user is asked to specify if the document has the chip"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdcheckviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDCheckViewController\/title","value":"IDCheckUIEMRTDCheckViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDCheckViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}