{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteDocumentCorrection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentCorrectionViewController","text":"IDCheckUIDocumentCorrectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentCorrection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentCorrection","preciseIdentifier":"s:10IDCheckLib0A18DocumentCorrectionV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckui\/controllerdidcompletedocumentcorrection(_:documentcorrection:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidCompleteDocumentCorrection(_:documentCorrection:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUIDocumentCorrectionViewControllerDelegate.controllerDidCompleteDocumentCorrection(_:documentCorrection:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidCompleteDocumentCorrection(_:documentCorrection:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteDocumentCorrection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentCorrectionViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentCorrectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentCorrection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentCorrection","preciseIdentifier":"s:10IDCheckLib0A18DocumentCorrectionV"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A2UIC39controllerDidCompleteDocumentCorrection_08documentH0yAA0a10UIDocumentH14ViewControllerC_0A3Lib0agH0VtF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIDocumentCorrectionViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/IDCheckUIDocumentCorrectionViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUIDocumentCorrectionViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIDocumentCorrectionViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/idcheckuidocumentcorrectionviewcontrollerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentCorrectionViewController":{"role":"symbol","title":"IDCheckUIDocumentCorrectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentcorrectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/controllerDidCompleteDocumentCorrection(_:documentCorrection:)":{"role":"symbol","title":"controllerDidCompleteDocumentCorrection(_:documentCorrection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteDocumentCorrection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentCorrectionViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentCorrectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentCorrection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentCorrection","preciseIdentifier":"s:10IDCheckLib0A18DocumentCorrectionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidCompleteDocumentCorrection(_:documentCorrection:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/controllerdidcompletedocumentcorrection(_:documentcorrection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentCorrectionViewController\/title","value":"IDCheckUIDocumentCorrectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentCorrectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}