{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteSelfieVerificationTutorial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationTutorialLegacyViewController","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckui\/controllerdidcompleteselfieverificationtutorial(_:)-1fm7z"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidCompleteSelfieVerificationTutorial(_:)-1fm7z","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate.controllerDidCompleteSelfieVerificationTutorial(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidCompleteSelfieVerificationTutorial(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteSelfieVerificationTutorial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationTutorialLegacyViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A2UIC47controllerDidCompleteSelfieVerificationTutorialyyAA0a8UISelfiehI20LegacyViewControllerCF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/controllerDidCompleteSelfieVerificationTutorial(_:)-1fm7z":{"role":"symbol","title":"controllerDidCompleteSelfieVerificationTutorial(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteSelfieVerificationTutorial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationTutorialLegacyViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidCompleteSelfieVerificationTutorial(_:)-1fm7z","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/controllerdidcompleteselfieverificationtutorial(_:)-1fm7z"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/idcheckuiselfieverificationtutoriallegacyviewcontrollerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialLegacyViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutoriallegacyviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialLegacyViewController\/title","value":"IDCheckUISelfieVerificationTutorialLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}