{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteSelfieVerificationTutorial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationTutorialViewController","text":"IDCheckUISelfieVerificationTutorialViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckui\/controllerdidcompleteselfieverificationtutorial(_:)-6t8md"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidCompleteSelfieVerificationTutorial(_:)-6t8md","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUISelfieVerificationTutorialViewControllerDelegate.controllerDidCompleteSelfieVerificationTutorial(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidCompleteSelfieVerificationTutorial(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteSelfieVerificationTutorial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUISelfieVerificationTutorialViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationTutorialViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A2UIC47controllerDidCompleteSelfieVerificationTutorialyyAA0a8UISelfiehI14ViewControllerCF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUISelfieVerificationTutorialViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutorialviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/IDCheckUISelfieVerificationTutorialViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUISelfieVerificationTutorialViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUISelfieVerificationTutorialViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/idcheckuiselfieverificationtutorialviewcontrollerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/controllerDidCompleteSelfieVerificationTutorial(_:)-6t8md":{"role":"symbol","title":"controllerDidCompleteSelfieVerificationTutorial(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteSelfieVerificationTutorial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUISelfieVerificationTutorialViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationTutorialViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidCompleteSelfieVerificationTutorial(_:)-6t8md","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/controllerdidcompleteselfieverificationtutorial(_:)-6t8md"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialViewController\/title","value":"IDCheckUISelfieVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}