{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteDocumentVerificationTutorial"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationTutorialViewController","text":"IDCheckUIDocumentVerificationTutorialViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"changeDocumentType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"_"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller\/controllerdidcompletedocumentverificationtutorial(_:changedocumenttype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController\/controllerDidCompleteDocumentVerificationTutorial(_:changeDocumentType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUIDocumentVerificationTutorialViewControllerDelegate.controllerDidCompleteDocumentVerificationTutorial(_:changeDocumentType:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidCompleteDocumentVerificationTutorial(_:changeDocumentType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteDocumentVerificationTutorial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationTutorialViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationTutorialViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"changeDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A36UIDocumentVerificationViewControllerC029controllerDidCompleteDocumentD8Tutorial_06changeJ4TypeyAA0acdkeF0C_SbtF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController\/IDCheckUIDocumentVerificationTutorialViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewController/IDCheckUIDocumentVerificationTutorialViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUIDocumentVerificationTutorialViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController\/IDCheckUIDocumentVerificationTutorialViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller\/idcheckuidocumentverificationtutorialviewcontrollerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewController/controllerDidCompleteDocumentVerificationTutorial(_:changeDocumentType:)":{"role":"symbol","title":"controllerDidCompleteDocumentVerificationTutorial(_:changeDocumentType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidCompleteDocumentVerificationTutorial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationTutorialViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationTutorialViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"changeDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController\/controllerDidCompleteDocumentVerificationTutorial(_:changeDocumentType:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller\/controllerdidcompletedocumentverificationtutorial(_:changedocumenttype:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/title","value":"IDCheckUIDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/title","value":"IDCheckUIDocumentVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}