{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/SQ","doc:\/\/ch.ti8m.idcheck.ui.library\/SH","doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UICollectionViewDataSource","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UICollectionViewDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIScrollViewDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/init(documentTypes:task:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/delegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/documentTypes","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/task"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/viewDidLoad()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDataSource-Implementations","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegate-Implementations","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegateFlowLayout-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"title":"IDCheckUIDocumentTypeSelectionViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentTypeSelectionViewController","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIScrollViewDelegate"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController":{"role":"symbol","title":"IDCheckUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.ui.library/14UIComponentSDK12ActivityHostP":{"type":"unresolvable","title":"UIComponentSDK.ActivityHost","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP"},"doc://ch.ti8m.idcheck.ui.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.ui.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/viewwillappear(_:)"},"doc://ch.ti8m.idcheck.ui.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP"},"doc://ch.ti8m.idcheck.ui.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SQ"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentTypeSelectionViewControllerDelegate","preciseIdentifier":"s:12IDCheckUILib0A45UIDocumentTypeSelectionViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/delegate"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UICollectionViewDelegate":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegate","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UICollectionViewDelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/UICollectionViewDelegateFlowLayout-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegateFlowLayout-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/uicollectionviewdelegateflowlayout-implementations"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UICollectionViewDelegateFlowLayout":{"type":"unresolvable","title":"UIKit.UICollectionViewDelegateFlowLayout","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UICollectionViewDelegateFlowLayout"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.ui.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SH"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/init(documentTypes:task:)":{"role":"symbol","title":"init(documentTypes:task:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckTaskDocumentVerify","preciseIdentifier":"s:10IDCheckLib0A18TaskDocumentVerifyV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/init(documentTypes:task:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/init(documenttypes:task:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/task":{"role":"symbol","title":"task","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckTaskDocumentVerify","preciseIdentifier":"s:10IDCheckLib0A18TaskDocumentVerifyV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/task","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/task"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/uicollectionviewdatasource-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/UICollectionViewDelegate-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/uicollectionviewdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/documentTypes":{"role":"symbol","title":"documentTypes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/documentTypes","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/documenttypes"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UICollectionViewDataSource":{"type":"unresolvable","title":"UIKit.UICollectionViewDataSource","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UICollectionViewDataSource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/viewDidLoad()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/viewWillAppear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDataSource-Implementations","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegate-Implementations","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegateFlowLayout-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController","text":"IDCheckUIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}