{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidRejectCameraAccess"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationViewController","text":"IDCheckUIDocumentVerificationViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckui\/controllerdidrejectcameraaccess(_:)-1ddko"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidRejectCameraAccess(_:)-1ddko","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUIDocumentVerificationViewControllerDelegate.controllerDidRejectCameraAccess(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidRejectCameraAccess(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidRejectCameraAccess"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A2UIC31controllerDidRejectCameraAccessyyAA0A36UIDocumentVerificationViewControllerCF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIDocumentVerificationViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/controllerDidRejectCameraAccess(_:)-1ddko":{"role":"symbol","title":"controllerDidRejectCameraAccess(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidRejectCameraAccess"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidRejectCameraAccess(_:)-1ddko","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/controllerdidrejectcameraaccess(_:)-1ddko"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/IDCheckUIDocumentVerificationViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUIDocumentVerificationViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIDocumentVerificationViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/idcheckuidocumentverificationviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/title","value":"IDCheckUIDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}