{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/preferredstatusbarstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/preferredstatusbarstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/preferredStatusBarStyle","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"title":"preferredStatusBarStyle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUINavigationController(py)preferredStatusBarStyle","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController":{"role":"symbol","title":"IDCheckUINavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUINavigationController"}],"abstract":[{"type":"text","text":"This is the main view controller of the IDCheckUI, ideally you should place an instance of this class as your window.rootViewController"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUINavigationController"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/preferredStatusBarStyle":{"role":"symbol","title":"preferredStatusBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/preferredStatusBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/preferredstatusbarstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"preferredStatusBarStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController\/title","value":"IDCheckUINavigationController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController\/fragments","value":[{"kind":"identifier","text":"IDCheckUINavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController~1preferredStatusBarStyle\/title","value":"preferredStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController~1preferredStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}