{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Current-version","level":2,"type":"heading","text":"Current version"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Version"}]},{"anchor":"Requirements","level":2,"type":"heading","text":"Requirements"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Minimum iOS version is: 13, the iOS SDK used for compiling is 16.0 (Xcode 14.2)"}]}]}]},{"anchor":"Support","level":2,"type":"heading","text":"Support"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is a summary of various iOS specific systems and how they are supported."}]},{"anchor":"Orientation","level":3,"type":"heading","text":"Orientation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently only portrait orientation is supported (with exception of the document scan module which is presented in landscape mode)."}]},{"anchor":"Dark-mode","level":3,"type":"heading","text":"Dark mode"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently not supported."}]},{"anchor":"Dynamic-type","level":3,"type":"heading","text":"Dynamic type"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently not supported."}]},{"anchor":"Tutorials","level":2,"type":"heading","text":"Tutorials"},{"type":"paragraph","inlineContent":[{"type":"text","text":"We have created step by step tutorial to make the integration easier - "},{"type":"reference","isActive":true,"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/tutorials\/Tutorial-Table-of-Contents"},{"type":"text","text":". The previously available integration guide is deprecated in favor of the tutorials, may not include the latest information, and will be removed in the next releases."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"IDCheckUILib","title":"IDCheckUILib","symbolKind":"module","role":"collection","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Integration-Guide","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Version"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIButton","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICancelProcessModalViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultMinorViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILabel","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILoadingIndicatorView","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"]},{"title":"Protocols","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICancelProcessModalViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewControllerDelegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewControllerDelegate"]},{"title":"Structures","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationPreferences","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationPreferences","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILabelStyle","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIPreferences","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationPreferences"]},{"title":"Enumerations","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/DocumentVerificationResult","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationSide","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewControllerButton","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIPreferredScanMode","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/SelfieVerificationResult"]}],"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/SelfieVerificationResult":{"role":"symbol","title":"SelfieVerificationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SelfieVerificationResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/SelfieVerificationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SelfieVerificationResult"}],"url":"\/documentation\/idcheckuilib\/selfieverificationresult"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUICancelProcessModalViewControllerDelegate":{"role":"symbol","title":"IDCheckUICancelProcessModalViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUICancelProcessModalViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICancelProcessModalViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUICancelProcessModalViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuicancelprocessmodalviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewControllerDelegate":{"role":"symbol","title":"IDCheckUISelfieVerificationInfoViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController":{"role":"symbol","title":"IDCheckUIAddressMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUICameraAccessViewController":{"role":"symbol","title":"IDCheckUICameraAccessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUICameraAccessViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUICameraAccessViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuicameraaccessviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUILabelStyle":{"role":"symbol","title":"IDCheckUILabelStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUILabelStyle"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILabelStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUILabelStyle"}],"url":"\/documentation\/idcheckuilib\/idcheckuilabelstyle"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckUIAddressVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressVerificationViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressVerificationViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUICancelProcessModalViewController":{"role":"symbol","title":"IDCheckUICancelProcessModalViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUICancelProcessModalViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICancelProcessModalViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUICancelProcessModalViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuicancelprocessmodalviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/tutorials/Tutorial-Table-of-Contents":{"role":"overview","title":"Introducing IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib is an UI layer on top of the IDCheckLib that simplifies it’s integration into your project."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/tutorials\/Tutorial-Table-of-Contents","kind":"overview","type":"topic","url":"\/tutorials\/tutorial-table-of-contents"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewControllerDelegate":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutorialviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDCheckViewController":{"role":"symbol","title":"IDCheckUIEMRTDCheckViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}],"abstract":[{"type":"text","text":"This controller appears at the very beginning of the process, just after the document selection screen, if the preferred scan mode is .ask, when the user is asked to specify if the document has the chip"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdcheckviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/DocumentVerificationResult":{"role":"symbol","title":"DocumentVerificationResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentVerificationResult"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/DocumentVerificationResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentVerificationResult"}],"url":"\/documentation\/idcheckuilib\/documentverificationresult"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUILoadingIndicatorView":{"role":"symbol","title":"IDCheckUILoadingIndicatorView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUILoadingIndicatorView"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILoadingIndicatorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUILoadingIndicatorView"}],"url":"\/documentation\/idcheckuilib\/idcheckuiloadingindicatorview"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewControllerDelegate":{"role":"symbol","title":"IDCheckUIViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUILibVersionNumber":{"role":"symbol","title":"IDCheckUILibVersionNumber","fragments":[{"kind":"identifier","text":"IDCheckUILibVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for IDCheckUILib."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILibVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuilibversionnumber"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressVerificationViewController":{"role":"symbol","title":"IDCheckUIAddressVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationSide":{"role":"symbol","title":"IDCheckUIDocumentVerificationSide","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationSide"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationSide","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationSide"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationside"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDSelectionViewControllerDelegate":{"role":"symbol","title":"IDCheckUIEMRTDSelectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdselectionviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckUIEMRTDVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController":{"role":"symbol","title":"IDCheckUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUILabel":{"role":"symbol","title":"IDCheckUILabel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUILabel"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUILabel"}],"url":"\/documentation\/idcheckuilib\/idcheckuilabel"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIPreferences":{"role":"symbol","title":"IDCheckUIPreferences","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIPreferences"}],"abstract":[{"type":"text","text":"IDCheckUIPreferences"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIPreferences","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIPreferences"}],"url":"\/documentation\/idcheckuilib\/idcheckuipreferences"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationResultMinorViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationResultMinorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultMinorViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultMinorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultMinorViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationresultminorviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewControllerDelegate":{"role":"symbol","title":"IDCheckUIDocumentVerificationTutorialViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationResultViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationResultViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationresultviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIIntroViewController":{"role":"symbol","title":"IDCheckUIIntroViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIIntroViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIIntroViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiintroviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIIntroViewControllerDelegate":{"role":"symbol","title":"IDCheckUIIntroViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIIntroViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIIntroViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiintroviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationLegacyViewControllerDelegate":{"role":"symbol","title":"IDCheckUISelfieVerificationLegacyViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationlegacyviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDVerificationPreferences":{"role":"symbol","title":"IDCheckUIEMRTDVerificationPreferences","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDVerificationPreferences"}],"abstract":[{"type":"text","text":"IDCheckUIEMRTDVerificationPreferences"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationPreferences","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDVerificationPreferences"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdverificationpreferences"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewControllerDelegate":{"role":"symbol","title":"IDCheckUIAddressMapViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressMapViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressMapViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewControllerDelegate":{"role":"symbol","title":"IDCheckUIDocumentVerificationViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDSelectionViewController":{"role":"symbol","title":"IDCheckUIEMRTDSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewController"}],"abstract":[{"type":"text","text":"This view controller is used to allow user the selection of the EMRTD mode"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationPreferences":{"role":"symbol","title":"IDCheckUIDocumentVerificationPreferences","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationPreferences"}],"abstract":[{"type":"text","text":"IDCheckUIDocumentVerificationPreferences"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationPreferences","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationPreferences"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationpreferences"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate":{"role":"symbol","title":"IDCheckUIDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDelegate"}],"abstract":[{"type":"text","text":"This delegate protocol is the main way of communication between the IDCheckUI and the integrating code"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDVerificationViewController":{"role":"symbol","title":"IDCheckUIEMRTDVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewController"}],"abstract":[{"type":"text","text":"This controller appears when the NFC is being read"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialLegacyViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutoriallegacyviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController":{"role":"symbol","title":"IDCheckUINavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUINavigationController"}],"abstract":[{"type":"text","text":"This is the main view controller of the IDCheckUI, ideally you should place an instance of this class as your window.rootViewController"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUINavigationController"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutoriallegacyviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentCorrectionViewControllerDelegate":{"role":"symbol","title":"IDCheckUIDocumentCorrectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentcorrectionviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDCheckViewControllerDelegate":{"role":"symbol","title":"IDCheckUIEMRTDCheckViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdcheckviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationResultViewControllerDelegate":{"role":"symbol","title":"IDCheckUISelfieVerificationResultViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationresultviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentCorrectionViewController":{"role":"symbol","title":"IDCheckUIDocumentCorrectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentcorrectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationPreferences":{"role":"symbol","title":"IDCheckUISelfieVerificationPreferences","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationPreferences"}],"abstract":[{"type":"text","text":"IDCheckUISelfieVerificationPreferences"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationPreferences","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationPreferences"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationpreferences"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationLegacyViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationlegacyviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIButton":{"role":"symbol","title":"IDCheckUIButton","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIButton"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIButton"}],"url":"\/documentation\/idcheckuilib\/idcheckuibutton"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewControllerDelegate":{"role":"symbol","title":"IDCheckUIDocumentVerificationInfoViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUICameraAccessViewControllerDelegate":{"role":"symbol","title":"IDCheckUICameraAccessViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUICameraAccessViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUICameraAccessViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuicameraaccessviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationResultViewControllerDelegate":{"role":"symbol","title":"IDCheckUIDocumentVerificationResultViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationresultviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialViewControllerDelegate":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewControllerDelegate"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewControllerDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutorialviewcontrollerdelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDSelectionViewControllerButton":{"role":"symbol","title":"IDCheckUIEMRTDSelectionViewControllerButton","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewControllerButton"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewControllerButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewControllerButton"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdselectionviewcontrollerbutton"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationResultViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationResultViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationresultviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/Integration-Guide":{"role":"article","title":"Integration Guide","abstract":[{"type":"text","text":"Step-by-step guide on how to integrate the IDCheckUILib into your app."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Integration-Guide","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/integration-guide"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUILibVersionString":{"role":"symbol","title":"IDCheckUILibVersionString","fragments":[{"kind":"identifier","text":"IDCheckUILibVersionString"}],"abstract":[{"type":"text","text":"Project version string for IDCheckUILib."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILibVersionString","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuilibversionstring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/Version":{"role":"article","title":"2.0.4","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Version","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/version"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIPreferredScanMode":{"role":"symbol","title":"IDCheckUIPreferredScanMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIPreferredScanMode"}],"abstract":[{"type":"text","text":"Defines which scan mode will be used when scanning the document. The .full mode scans the document, together with hologram etc. The .preNFC mode additionally reads the NFC chip of the document. The .ask mode will display a view to the user asking them if their document has the chip, and continue with the best scanning mode depending on the user choice."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIPreferredScanMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIPreferredScanMode"}],"url":"\/documentation\/idcheckuilib\/idcheckuipreferredscanmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Integration-Guide","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/Version"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIButton","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICancelProcessModalViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultMinorViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILabel","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILoadingIndicatorView","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"]},{"title":"Protocols","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate"]},{"title":"Variables","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILibVersionNumber","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUILibVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController\/title","value":"IDCheckUIDocumentVerificationInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController\/title","value":"IDCheckUISelfieVerificationInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/title","value":"IDCheckUIAddressMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUICameraAccessViewController\/title","value":"IDCheckUICameraAccessViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUICameraAccessViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUICameraAccessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUICancelProcessModalViewController\/title","value":"IDCheckUICancelProcessModalViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUICancelProcessModalViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUICancelProcessModalViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialViewController\/title","value":"IDCheckUISelfieVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDCheckViewController\/title","value":"IDCheckUIEMRTDCheckViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDCheckViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUILoadingIndicatorView\/title","value":"IDCheckUILoadingIndicatorView"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUILoadingIndicatorView\/fragments","value":[{"kind":"identifier","text":"IDCheckUILoadingIndicatorView"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressVerificationViewController\/title","value":"IDCheckUIAddressVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIAddressVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/title","value":"IDCheckUIDocumentVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUILabel\/title","value":"IDCheckUILabel"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUILabel\/fragments","value":[{"kind":"identifier","text":"IDCheckUILabel"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultMinorViewController\/title","value":"IDCheckUIDocumentVerificationResultMinorViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultMinorViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultMinorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationResultViewController\/title","value":"IDCheckUISelfieVerificationResultViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationResultViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIIntroViewController\/title","value":"IDCheckUIIntroViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIIntroViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIIntroViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/title","value":"IDCheckUIDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDSelectionViewController\/title","value":"IDCheckUIEMRTDSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate\/title","value":"IDCheckUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDVerificationViewController\/title","value":"IDCheckUIEMRTDVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialLegacyViewController\/title","value":"IDCheckUISelfieVerificationTutorialLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController\/title","value":"IDCheckUINavigationController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController\/fragments","value":[{"kind":"identifier","text":"IDCheckUINavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentCorrectionViewController\/title","value":"IDCheckUIDocumentCorrectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentCorrectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationLegacyViewController\/title","value":"IDCheckUISelfieVerificationLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIButton\/title","value":"IDCheckUIButton"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIButton\/fragments","value":[{"kind":"identifier","text":"IDCheckUIButton"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultViewController\/title","value":"IDCheckUIDocumentVerificationResultViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}