{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUINavigationController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuinavigationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuinavigationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(cs)UINavigationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/SQ","doc:\/\/ch.ti8m.idcheck.ui.library\/SH","doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the main view controller of the IDCheckUI, ideally you should place an instance of this class as your window.rootViewController"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUINavigationController"}],"title":"IDCheckUINavigationController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUINavigationController","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUINavigationController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/loadingIndicatorView","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/preferredStatusBarStyle"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/dismissPresentedViewController()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/hideLoadingIndicator()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/presentViewController(_:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/showLoadingIndicator()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/viewDidLoad()"]}],"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/initwithcoder:"},"doc://ch.ti8m.idcheck.ui.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/dismissPresentedViewController()":{"role":"symbol","title":"dismissPresentedViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissPresentedViewController"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/dismissPresentedViewController()","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/dismisspresentedviewcontroller()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController":{"role":"symbol","title":"IDCheckUINavigationController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUINavigationController"}],"abstract":[{"type":"text","text":"This is the main view controller of the IDCheckUI, ideally you should place an instance of this class as your window.rootViewController"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUINavigationController"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller"},"doc://ch.ti8m.idcheck.ui.library/14UIComponentSDK12ActivityHostP":{"type":"unresolvable","title":"UIComponentSDK.ActivityHost","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/preferredStatusBarStyle":{"role":"symbol","title":"preferredStatusBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/preferredStatusBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/preferredstatusbarstyle"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.ui.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SQ"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/initWithRootViewController:":{"role":"symbol","title":"initWithRootViewController:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRootViewController:"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithRootViewController:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRootViewController:"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/initwithrootviewcontroller:"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/loadingIndicatorView":{"role":"symbol","title":"loadingIndicatorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadingIndicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/loadingIndicatorView","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/loadingindicatorview"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/presentViewController(_:)":{"role":"symbol","title":"presentViewController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/presentViewController(_:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/presentviewcontroller(_:)"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.ui.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/initwithnibname:bundle:"},"doc://ch.ti8m.idcheck.ui.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.ui.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SH"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.ui.library/objc(cs)UINavigationController":{"type":"unresolvable","title":"UINavigationController","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(cs)UINavigationController"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/hideLoadingIndicator()":{"role":"symbol","title":"hideLoadingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideLoadingIndicator"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/hideLoadingIndicator()","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/hideloadingindicator()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/showLoadingIndicator()":{"role":"symbol","title":"showLoadingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingIndicator"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/showLoadingIndicator()","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/showloadingindicator()"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.ui.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/initWithNavigationBarClass:toolbarClass:":{"role":"symbol","title":"initWithNavigationBarClass:toolbarClass:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNavigationBarClass:toolbarClass:"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithNavigationBarClass:toolbarClass:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNavigationBarClass:toolbarClass:"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/initwithnavigationbarclass:toolbarclass:"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUINavigationController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idcheckuilib\/idcheckuinavigationcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUINavigationController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUINavigationController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUINavigationController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/preferredStatusBarStyle"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithCoder:","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithNavigationBarClass:toolbarClass:","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithNibName:bundle:","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/initWithRootViewController:","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUINavigationController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(cs)UINavigationController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUINavigationController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController\/title","value":"IDCheckUINavigationController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController\/fragments","value":[{"kind":"identifier","text":"IDCheckUINavigationController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController~1preferredStatusBarStyle\/title","value":"preferredStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController~1preferredStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUINavigationController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}