{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/SQ","doc:\/\/ch.ti8m.idcheck.ui.library\/SH","doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/init(documentType:side:task:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/delegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/documentType","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/side","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/task"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/viewDidAppear(_:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"title":"IDCheckUIDocumentVerificationTutorialViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationTutorialViewController","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationTutorialViewControllerDelegate","preciseIdentifier":"s:12IDCheckUILib0A52UIDocumentVerificationTutorialViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/delegate"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.ui.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.ui.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP"},"doc://ch.ti8m.idcheck.ui.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SH"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/viewdidappear(_:)"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/side":{"role":"symbol","title":"side","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"side"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationSide","preciseIdentifier":"s:12IDCheckUILib0A26UIDocumentVerificationSideO"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/side","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/side"},"doc://ch.ti8m.idcheck.ui.library/14UIComponentSDK12ActivityHostP":{"type":"unresolvable","title":"UIComponentSDK.ActivityHost","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/documentType":{"role":"symbol","title":"documentType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/documentType","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/documenttype"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.ui.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.ui.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SQ"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/init(documentType:side:task:)":{"role":"symbol","title":"init(documentType:side:task:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"side"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationSide","preciseIdentifier":"s:12IDCheckUILib0A26UIDocumentVerificationSideO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckTaskDocumentVerify","preciseIdentifier":"s:10IDCheckLib0A18TaskDocumentVerifyV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/init(documentType:side:task:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/init(documenttype:side:task:)"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController":{"role":"symbol","title":"IDCheckUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController/task":{"role":"symbol","title":"task","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckTaskDocumentVerify","preciseIdentifier":"s:10IDCheckLib0A18TaskDocumentVerifyV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/task","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller\/task"},"doc://ch.ti8m.idcheck.ui.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUIDocumentVerificationTutorialViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/viewDidAppear(_:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController","text":"IDCheckUIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/title","value":"IDCheckUIDocumentVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}