{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":" "},{"kind":"internalParam","text":"locations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/locationmanager(_:didupdatelocations:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/locationmanager(_:didupdatelocations:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/locationManager(_:didUpdateLocations:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CLLocationManagerDelegate.locationManager(_:didUpdateLocations:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"title":"locationManager(_:didUpdateLocations:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@IDCheckUILib@objc(cs)IDCheckUIAddressMapViewController(im)locationManager:didUpdateLocations:","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/CLLocationManagerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController":{"role":"symbol","title":"IDCheckUIAddressMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController/locationManager(_:didUpdateLocations:)":{"role":"symbol","title":"locationManager(_:didUpdateLocations:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/locationManager(_:didUpdateLocations:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/locationmanager(_:didupdatelocations:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController/CLLocationManagerDelegate-Implementations":{"role":"collectionGroup","title":"CLLocationManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/CLLocationManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/cllocationmanagerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateLocations:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<CLLocation *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"locations"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/title","value":"IDCheckUIAddressMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController~1locationManager(_:didUpdateLocations:)\/title","value":"locationManager:didUpdateLocations:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController~1locationManager(_:didUpdateLocations:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}