{"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/uicollectionviewdelegateflowlayout-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/uicollectionviewdelegateflowlayout-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDelegateFlowLayout-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:insetForSectionAt:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:referenceSizeForHeaderInSection:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:sizeForItemAt:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"IDCheckUILib"}],"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations"},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/collectionView(_:layout:insetForSectionAt:)":{"role":"symbol","title":"collectionView(_:layout:insetForSectionAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"insetForSectionAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:insetForSectionAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:insetForSectionAtIndex:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:layout:insetforsectionat:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/collectionView(_:layout:minimumLineSpacingForSectionAt:)":{"role":"symbol","title":"collectionView(_:layout:minimumLineSpacingForSectionAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumLineSpacingForSectionAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:layout:minimumlinespacingforsectionat:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/collectionView(_:layout:sizeForItemAt:)":{"role":"symbol","title":"collectionView(_:layout:sizeForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:sizeForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:layout:sizeforitemat:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)":{"role":"symbol","title":"collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumInteritemSpacingForSectionAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:layout:minimuminteritemspacingforsectionat:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/collectionView(_:layout:referenceSizeForHeaderInSection:)":{"role":"symbol","title":"collectionView(_:layout:referenceSizeForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"referenceSizeForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:referenceSizeForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:referenceSizeForHeaderInSection:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:layout:referencesizeforheaderinsection:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:insetForSectionAt:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:referenceSizeForHeaderInSection:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:layout:sizeForItemAt:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:insetForSectionAt:)\/title","value":"collectionView:layout:insetForSectionAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:insetForSectionAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:insetForSectionAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:minimumLineSpacingForSectionAt:)\/title","value":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:minimumLineSpacingForSectionAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/title","value":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:referenceSizeForHeaderInSection:)\/title","value":"collectionView:layout:referenceSizeForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:layout:referenceSizeForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForHeaderInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}