{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/SQ","doc:\/\/ch.ti8m.idcheck.ui.library\/SH","doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/init(documentType:side:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/delegate","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/documentType","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/side"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"title":"IDCheckUIDocumentVerificationInfoViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentVerificationInfoViewController","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController/documentType":{"role":"symbol","title":"documentType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/documentType","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller\/documenttype"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController/side":{"role":"symbol","title":"side","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"side"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationSide","preciseIdentifier":"s:12IDCheckUILib0A26UIDocumentVerificationSideO"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/side","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller\/side"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.ui.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SQ"},"doc://ch.ti8m.idcheck.ui.library/14UIComponentSDK12ActivityHostP":{"type":"unresolvable","title":"UIComponentSDK.ActivityHost","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP"},"doc://ch.ti8m.idcheck.ui.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.ui.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationInfoViewControllerDelegate","preciseIdentifier":"s:12IDCheckUILib0A48UIDocumentVerificationInfoViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller\/delegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.ui.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SH"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController":{"role":"symbol","title":"IDCheckUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController/init(documentType:side:)":{"role":"symbol","title":"init(documentType:side:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"side"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUIDocumentVerificationSide","preciseIdentifier":"s:12IDCheckUILib0A26UIDocumentVerificationSideO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/init(documentType:side:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller\/init(documenttype:side:)"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.ui.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUIDocumentVerificationInfoViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController","text":"IDCheckUIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController\/title","value":"IDCheckUIDocumentVerificationInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}