{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuiviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuiviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultMinorViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/SQ","doc:\/\/ch.ti8m.idcheck.ui.library\/SH","doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/fullscreen","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/leftBarButtonItem","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/localizedTitle","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/preferredStatusBarStyle","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/rightBarButtonItem"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"title":"IDCheckUIViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIIntroViewController":{"role":"symbol","title":"IDCheckUIIntroViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIIntroViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIIntroViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiintroviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUICameraAccessViewController":{"role":"symbol","title":"IDCheckUICameraAccessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUICameraAccessViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUICameraAccessViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuicameraaccessviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDVerificationViewController":{"role":"symbol","title":"IDCheckUIEMRTDVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewController"}],"abstract":[{"type":"text","text":"This controller appears when the NFC is being read"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController/localizedTitle":{"role":"symbol","title":"localizedTitle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/localizedTitle","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller\/localizedtitle"},"doc://ch.ti8m.idcheck.ui.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SH"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment"},"doc://ch.ti8m.idcheck.ui.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController":{"role":"symbol","title":"IDCheckUIAddressMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController/fullscreen":{"role":"symbol","title":"fullscreen","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/fullscreen","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller\/fullscreen"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDCheckViewController":{"role":"symbol","title":"IDCheckUIEMRTDCheckViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}],"abstract":[{"type":"text","text":"This controller appears at the very beginning of the process, just after the document selection screen, if the preferred scan mode is .ask, when the user is asked to specify if the document has the chip"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdcheckviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController":{"role":"symbol","title":"IDCheckUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressVerificationViewController":{"role":"symbol","title":"IDCheckUIAddressVerificationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressVerificationViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressVerificationViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressverificationviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationInfoViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationinfoviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialLegacyViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutoriallegacyviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.ui.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationResultMinorViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationResultMinorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultMinorViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultMinorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultMinorViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationresultminorviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationtutorialviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController/preferredStatusBarStyle":{"role":"symbol","title":"preferredStatusBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/preferredStatusBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller\/preferredstatusbarstyle"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.ui.library/14UIComponentSDK12ActivityHostP":{"type":"unresolvable","title":"UIComponentSDK.ActivityHost","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP"},"doc://ch.ti8m.idcheck.ui.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SQ"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentCorrectionViewController":{"role":"symbol","title":"IDCheckUIDocumentCorrectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentcorrectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationResultViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationResultViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationresultviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentVerificationResultViewController":{"role":"symbol","title":"IDCheckUIDocumentVerificationResultViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumentverificationresultviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(cs)UIViewController"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationLegacyViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationLegacyViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationlegacyviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIEMRTDSelectionViewController":{"role":"symbol","title":"IDCheckUIEMRTDSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewController"}],"abstract":[{"type":"text","text":"This view controller is used to allow user the selection of the EMRTD mode"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiemrtdselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController/leftBarButtonItem":{"role":"symbol","title":"leftBarButtonItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftBarButtonItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/leftBarButtonItem","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller\/leftbarbuttonitem"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController/rightBarButtonItem":{"role":"symbol","title":"rightBarButtonItem","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightBarButtonItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/rightBarButtonItem","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller\/rightbarbuttonitem"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationTutorialViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationTutorialViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationtutorialviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/preferredStatusBarStyle"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUICameraAccessViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentCorrectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultMinorViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationTutorialViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDCheckViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIEMRTDVerificationViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIIntroViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationResultViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialLegacyViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationTutorialViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIIntroViewController\/title","value":"IDCheckUIIntroViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIIntroViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIIntroViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUICameraAccessViewController\/title","value":"IDCheckUICameraAccessViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUICameraAccessViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUICameraAccessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDVerificationViewController\/title","value":"IDCheckUIEMRTDVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/title","value":"IDCheckUIAddressMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/title","value":"IDCheckUIDocumentVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDCheckViewController\/title","value":"IDCheckUIEMRTDCheckViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDCheckViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDCheckViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressVerificationViewController\/title","value":"IDCheckUIAddressVerificationViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressVerificationViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIAddressVerificationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController\/title","value":"IDCheckUIDocumentVerificationInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationInfoViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialLegacyViewController\/title","value":"IDCheckUISelfieVerificationTutorialLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialLegacyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultMinorViewController\/title","value":"IDCheckUIDocumentVerificationResultMinorViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultMinorViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultMinorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/title","value":"IDCheckUIDocumentVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationTutorialViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController~1preferredStatusBarStyle\/title","value":"preferredStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController~1preferredStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"preferredStatusBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentCorrectionViewController\/title","value":"IDCheckUIDocumentCorrectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentCorrectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentCorrectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController\/title","value":"IDCheckUISelfieVerificationInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationResultViewController\/title","value":"IDCheckUISelfieVerificationResultViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationResultViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationResultViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultViewController\/title","value":"IDCheckUIDocumentVerificationResultViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentVerificationResultViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentVerificationResultViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationLegacyViewController\/title","value":"IDCheckUISelfieVerificationLegacyViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationLegacyViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationLegacyViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDSelectionViewController\/title","value":"IDCheckUIEMRTDSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIEMRTDSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIEMRTDSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialViewController\/title","value":"IDCheckUISelfieVerificationTutorialViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationTutorialViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationTutorialViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}