{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject","doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP","doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP","doc:\/\/ch.ti8m.idcheck.ui.library\/SQ","doc:\/\/ch.ti8m.idcheck.ui.library\/SH","doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP","doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment","doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"title":"IDCheckUISelfieVerificationInfoViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@IDCheckUILib@objc(cs)IDCheckUISelfieVerificationInfoViewController","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s28CustomDebugStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIViewController":{"role":"symbol","title":"IDCheckUIViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIResponderStandardEditActions"},"doc://ch.ti8m.idcheck.ui.library/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s8SendableP"},"doc://ch.ti8m.idcheck.ui.library/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s23CustomStringConvertibleP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSObject"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSExtensionRequestHandling"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewController":{"role":"symbol","title":"IDCheckUISelfieVerificationInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIUserActivityRestoring"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/init()","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller\/init()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller\/viewdidload()"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIFocusEnvironment"},"doc://ch.ti8m.idcheck.ui.library/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SQ"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIAppearanceContainer"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUISelfieVerificationInfoViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IDCheckUISelfieVerificationInfoViewControllerDelegate","preciseIdentifier":"s:12IDCheckUILib0A46UISelfieVerificationInfoViewControllerDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiselfieverificationinfoviewcontroller\/delegate"},"doc://ch.ti8m.idcheck.ui.library/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/s7CVarArgP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIStateRestoring"},"doc://ch.ti8m.idcheck.ui.library/14UIComponentSDK12ActivityHostP":{"type":"unresolvable","title":"UIComponentSDK.ActivityHost","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/14UIComponentSDK12ActivityHostP"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIPasteConfigurationSupporting"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIContentContainer"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://ch.ti8m.idcheck.ui.library/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/SH"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)NSCoding"},"doc://ch.ti8m.idcheck.ui.library/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUISelfieVerificationInfoViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUISelfieVerificationInfoViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController","text":"IDCheckUIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/title","value":"IDCheckUIViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController\/title","value":"IDCheckUISelfieVerificationInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUISelfieVerificationInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUISelfieVerificationInfoViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}