{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidSelect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentTypeSelectionViewController","text":"IDCheckUIDocumentTypeSelectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentType"},{"kind":"text","text":": IDCheckLib"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckui\/controllerdidselect(_:documenttype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidSelect(_:documentType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IDCheckUIDocumentTypeSelectionViewControllerDelegate.controllerDidSelect(_:documentType:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"controllerDidSelect(_:documentType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidSelect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentTypeSelectionViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentTypeSelectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentType"},{"kind":"text","text":": IDCheckLib"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:12IDCheckUILib0A2UIC19controllerDidSelect_12documentTypeyAA0a10UIDocumentH23SelectionViewControllerC_0A3Lib0a8DocumentH0OtF","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIDocumentTypeSelectionViewControllerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/controllerDidSelect(_:documentType:)":{"role":"symbol","title":"controllerDidSelect(_:documentType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"controllerDidSelect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIDocumentTypeSelectionViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIDocumentTypeSelectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentType"},{"kind":"text","text":": IDCheckLib"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"IDCheckDocumentType","preciseIdentifier":"s:10IDCheckLib0A12DocumentTypeO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/controllerDidSelect(_:documentType:)","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/controllerdidselect(_:documenttype:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI":{"role":"symbol","title":"IDCheckUI","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUI"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUI"}],"url":"\/documentation\/idcheckuilib\/idcheckui"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUI/IDCheckUIDocumentTypeSelectionViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"IDCheckUIDocumentTypeSelectionViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUI\/IDCheckUIDocumentTypeSelectionViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckui\/idcheckuidocumenttypeselectionviewcontrollerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/title","value":"IDCheckUI"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUI\/fragments","value":[{"kind":"identifier","text":"IDCheckUI"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}