{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/locationmanagerdidchangeauthorization(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/locationmanagerdidchangeauthorization(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/locationManagerDidChangeAuthorization(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CLLocationManagerDelegate.locationManagerDidChangeAuthorization(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"role":"symbol","title":"locationManagerDidChangeAuthorization(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@IDCheckUILib@objc(cs)IDCheckUIAddressMapViewController(im)locationManagerDidChangeAuthorization:","extendedModule":"IDCheckUILib","modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/CLLocationManagerDelegate-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController/locationManagerDidChangeAuthorization(_:)":{"role":"symbol","title":"locationManagerDidChangeAuthorization(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/locationManagerDidChangeAuthorization(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/locationmanagerdidchangeauthorization(_:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController/CLLocationManagerDelegate-Implementations":{"role":"collectionGroup","title":"CLLocationManagerDelegate Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController\/CLLocationManagerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller\/cllocationmanagerdelegate-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIAddressMapViewController":{"role":"symbol","title":"IDCheckUIAddressMapViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIAddressMapViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuiaddressmapviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"locationManagerDidChangeAuthorization:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"manager"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController~1locationManagerDidChangeAuthorization(_:)\/title","value":"locationManagerDidChangeAuthorization:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController~1locationManagerDidChangeAuthorization(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/title","value":"IDCheckUIAddressMapViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIAddressMapViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIAddressMapViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}