{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingIndicator"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidelegate\/showloadingindicator()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidelegate\/showloadingindicator()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/showLoadingIndicator()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method is invoked when the SDK is processing. The integrating code gets a chance to improve the UI experiece by presenting a loading indicator to the user."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"showLoadingIndicator"}],"role":"symbol","title":"showLoadingIndicator()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingIndicator"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@IDCheckUILib@objc(pl)IDCheckUIDelegate(im)showLoadingIndicator","required":true,"modules":[{"name":"IDCheckUILib"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/showLoadingIndicator()":{"navigatorTitle":[{"kind":"identifier","text":"showLoadingIndicator"}],"role":"symbol","title":"showLoadingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingIndicator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK is processing. The integrating code gets a chance to improve the UI experiece by presenting a loading indicator to the user."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/showLoadingIndicator()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/showloadingindicator()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate":{"role":"symbol","title":"IDCheckUIDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDelegate"}],"abstract":[{"type":"text","text":"This delegate protocol is the main way of communication between the IDCheckUI and the integrating code"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showLoadingIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showLoadingIndicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showLoadingIndicator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1showLoadingIndicator()\/title","value":"showLoadingIndicator"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1showLoadingIndicator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showLoadingIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate\/title","value":"IDCheckUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}