{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:cellForItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:cellForItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"title":"collectionView(_:cellForItemAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@IDCheckUILib@objc(cs)IDCheckUIDocumentTypeSelectionViewController(im)collectionView:cellForItemAtIndexPath:","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDataSource-Implementations"]]},"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/collectionView(_:cellForItemAt:)":{"role":"symbol","title":"collectionView(_:cellForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/collectionView(_:cellForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/collectionview(_:cellforitemat:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController":{"role":"symbol","title":"IDCheckUIDocumentTypeSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}],"url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDocumentTypeSelectionViewController/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDocumentTypeSelectionViewController\/UICollectionViewDataSource-Implementations","kind":"article","type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidocumenttypeselectionviewcontroller\/uicollectionviewdatasource-implementations"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:cellForItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellForItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/title","value":"IDCheckUIDocumentTypeSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDocumentTypeSelectionViewController\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDocumentTypeSelectionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}