{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/idcheckuilib\/idcheckuidelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/idcheckuilib\/idcheckuidelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This delegate protocol is the main way of communication between the IDCheckUI and the integrating code"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDelegate"}],"title":"IDCheckUIDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@IDCheckUILib@objc(pl)IDCheckUIDelegate","modules":[{"name":"IDCheckUILib"}],"navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDelegate"}]},"hierarchy":{"paths":[["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/didCompleteProcess(result:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/dismissPresentedViewController()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/hideLoadingIndicator()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/presentViewController(_:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/presentWaitingViewController()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/showLoadingIndicator()"]}],"references":{"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib":{"role":"collection","title":"IDCheckUILib","abstract":[{"type":"text","text":"IDCheckUILib - UI module for IDCheckLib"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib","kind":"symbol","type":"topic","url":"\/documentation\/idcheckuilib"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/presentViewController(_:)":{"navigatorTitle":[{"kind":"identifier","text":"presentViewController:"}],"role":"symbol","title":"presentViewController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDCheckUIViewController","preciseIdentifier":"c:@M@IDCheckUILib@objc(cs)IDCheckUIViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK presents a view controller. During the process the SDK will show different view controllers for different functionality, for example document scan, NFC read or liveness. This delegate method let’s the integrating code react when this happens."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/presentViewController(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/presentviewcontroller(_:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/showLoadingIndicator()":{"navigatorTitle":[{"kind":"identifier","text":"showLoadingIndicator"}],"role":"symbol","title":"showLoadingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLoadingIndicator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK is processing. The integrating code gets a chance to improve the UI experiece by presenting a loading indicator to the user."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/showLoadingIndicator()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/showloadingindicator()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/didCompleteProcess(result:)":{"navigatorTitle":[{"kind":"identifier","text":"didCompleteProcessWithResult:"}],"role":"symbol","title":"didCompleteProcess(result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteProcess"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK completes the process. The process can finish successfully or fail, this is communicated by the result parameter."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/didCompleteProcess(result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/didcompleteprocess(result:)"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate":{"role":"symbol","title":"IDCheckUIDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDelegate"}],"abstract":[{"type":"text","text":"This delegate protocol is the main way of communication between the IDCheckUI and the integrating code"}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IDCheckUIDelegate"}],"url":"\/documentation\/idcheckuilib\/idcheckuidelegate"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/hideLoadingIndicator()":{"navigatorTitle":[{"kind":"identifier","text":"hideLoadingIndicator"}],"role":"symbol","title":"hideLoadingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideLoadingIndicator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK finishes processing, if a loading indicator was presented by the integrating code, now is the time to dismiss it."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/hideLoadingIndicator()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/hideloadingindicator()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/presentWaitingViewController()":{"navigatorTitle":[{"kind":"identifier","text":"presentWaitingViewController"}],"role":"symbol","title":"presentWaitingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentWaitingViewController"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK is processing, giving the integrating code a chance to present a waiting screen if needed."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/presentWaitingViewController()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/presentwaitingviewcontroller()"},"doc://ch.ti8m.idcheck.ui.library/documentation/IDCheckUILib/IDCheckUIDelegate/dismissPresentedViewController()":{"navigatorTitle":[{"kind":"identifier","text":"dismissPresentedViewController"}],"role":"symbol","title":"dismissPresentedViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissPresentedViewController"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is invoked when the SDK dismisses a view controller, and gives the integrating code a chance to react when this happens."}],"identifier":"doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/dismissPresentedViewController()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/idcheckuilib\/idcheckuidelegate\/dismisspresentedviewcontroller()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IDCheckUIDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IDCheckUIDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/didCompleteProcess(result:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/dismissPresentedViewController()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/hideLoadingIndicator()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/presentViewController(_:)","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/presentWaitingViewController()","doc:\/\/ch.ti8m.idcheck.ui.library\/documentation\/IDCheckUILib\/IDCheckUIDelegate\/showLoadingIndicator()"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDCheckUIDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1presentViewController(_:)\/title","value":"presentViewController:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1presentViewController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1showLoadingIndicator()\/title","value":"showLoadingIndicator"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1showLoadingIndicator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showLoadingIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1didCompleteProcess(result:)\/title","value":"didCompleteProcessWithResult:"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1didCompleteProcess(result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCompleteProcessWithResult:"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate\/title","value":"IDCheckUIDelegate"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate\/fragments","value":[{"kind":"identifier","text":"IDCheckUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1hideLoadingIndicator()\/title","value":"hideLoadingIndicator"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1hideLoadingIndicator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideLoadingIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1presentWaitingViewController()\/title","value":"presentWaitingViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1presentWaitingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWaitingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1dismissPresentedViewController()\/title","value":"dismissPresentedViewController"},{"op":"replace","path":"\/references\/doc:~1~1ch.ti8m.idcheck.ui.library~1documentation~1IDCheckUILib~1IDCheckUIDelegate~1dismissPresentedViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissPresentedViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}